### ISSUE TITLE
tvOS Support

### ISSUE THREAD

**Issue by ANGOmarcello** [arcam/CocoaUPnP#25]
Would be cool to use this on tvOS instead of upnpx. But currently does not work.

**Comment by squarefrog** [comment]
We welcome Pull Requests if that is something you'd like to see.

**Comment by haseebyf** [comment]
The problem is due to Ono. Considering Ono is no longer maintained, I think CocoaUPNP needs to move away from it. I suggest using https://github.com/cezheng/Fuzi instead. 

I have used CocoaUPNP in my tvOS project by removing dependancy on Ono and then separately adding Ono source files. 

CocoaUPNP is more efficient by the way, as compared to upnpx.

**Comment by squarefrog** [comment]
Hmmm this would be a fairly large non trivial change. I'd have to look at the swift -> objective c comparability, although I don't immediately see anything that is a blocker.

**Comment by squarefrog** [comment]
Added in https://github.com/arcam/CocoaUPnP/pull/52

**Comment by ANGOmarcello** [comment]
I totally forgot about this thanks a lot, maybe I will revive my old project.
